Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
import os
import sys
import glob
import time

import numpy as np
from astropy.io import fits
import matplotlib.pyplot as plt
from astropy import units as u
import zipfile
import urllib.request

from jwst.pipeline import Detector1Pipeline, Image2Pipeline

from nrm_analysis.misctools import utils
import nrm_analysis
from nrm_analysis.fringefitting.LG_Model import NRM_Model
from nrm_analysis import nrm_core, InstrumentData
from nrm_analysis import find_affine2d_parameters as FAP
from nrm_analysis.misctools.implane2oifits import calibrate_oifits

from nrm_analysis.misctools.utils import Affine2d
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 16>[0;34m()[0m
[1;32m     12[0m [38;5;28;01mimport[39;00m [38;5;21;01murllib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrequest[39;00m
[1;32m     14[0m [38;5;28;01mfrom[39;00m [38;5;21;01mjwst[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpipeline[39;00m [38;5;28;01mimport[39;00m Detector1Pipeline, Image2Pipeline
[0;32m---> 16[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnrm_analysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmisctools[39;00m [38;5;28;01mimport[39;00m utils
[1;32m     17[0m [38;5;28;01mimport[39;00m [38;5;21;01mnrm_analysis[39;00m
[1;32m     18[0m [38;5;28;01mfrom[39;00m [38;5;21;01mnrm_analysis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfringefitting[39;00m[38;5;21;01m.[39;00m[38;5;21;01mLG_Model[39;00m [38;5;28;01mimport[39;00m NRM_Model

[0;31mModuleNotFoundError[0m: No module named 'nrm_analysis'
ModuleNotFoundError: No module named 'nrm_analysis'

